require 'torch'
require 'libjzt'
require 'nn'
require 'cutorch'

include('util.lua')

include('CBCA.lua')
include('ConvJoin.lua')
include('ConvSplit.lua')
include('L2Pooling.lua')
include('Linear.lua')
include('Linear1.lua')
include('Mul.lua')
include('Relu.lua')
include('Sequential.lua')
include('SpatialBias.lua')
include('SpatialConvolution1.lua')
include('SpatialConvolution1_fw.lua')
include('SpatialLogSoftMax.lua')
include('SpatialMaxout.lua')
include('SpatialNormalization.lua')
include('SpatialRandnPadding.lua')
include('Sqrt.lua')
include('StereoJoin.lua')
include('StereoJoin2.lua')
include('Tanh.lua')
include('Dropout.lua')
include('PairwiseDistance.lua')
include('SpatialConvolutionMMminibatch.lua')

include('ClassNLLCriterion.lua')
include('HuberCost.lua')
include('KLDivergence.lua')
include('L1Cost.lua')
include('MSECost.lua')
include('Margin1Loss.lua')
include('Margin2Loss.lua')
include('SpatialClassNLLCriterion.lua')
include('SpatialKernelNLLCriterion.lua')
include('HingeEmbeddingCriterion.lua')
